development:
  adapter: postgresql
  encoding: unicode
  database: moika_development
  pool: 5
  host: localhost
  username: vatagin
  password: vat123
test:
  adapter: postgresql
  encoding: unicode
  database: moika_test
  pool: 5
  host: localhost
  username: vatagin
  password: vat123
production:
  adapter: postgresql
  encoding: unicode
  database: moika_production
  pool: 5
  host: localhost
  username: vatagin
  password: vat123
