development:
  server: "http://localhost:9292/faye"
  #server: "http://test.moika-77.ru:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://test.moika-77.ru:9292/faye"
  secret_token: "f3a0dbebbd47d423778a23939a99c09846ef5bfdec2d3e5e442a924287d58815"
  signature_expiration: 3600 # one hour
