require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarWashesController do

  # This should return the minimal set of attributes required to create a valid
  # CarWash. As you add validations to CarWash, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CarWashesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all car_washes as @car_washes" do
      car_wash = CarWash.create! valid_attributes
      get :index, {}, valid_session
      assigns(:car_washes).should eq([car_wash])
    end
  end

  describe "GET show" do
    it "assigns the requested car_wash as @car_wash" do
      car_wash = CarWash.create! valid_attributes
      get :show, {:id => car_wash.to_param}, valid_session
      assigns(:car_wash).should eq(car_wash)
    end
  end

  describe "GET new" do
    it "assigns a new car_wash as @car_wash" do
      get :new, {}, valid_session
      assigns(:car_wash).should be_a_new(CarWash)
    end
  end

  describe "GET edit" do
    it "assigns the requested car_wash as @car_wash" do
      car_wash = CarWash.create! valid_attributes
      get :edit, {:id => car_wash.to_param}, valid_session
      assigns(:car_wash).should eq(car_wash)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CarWash" do
        expect {
          post :create, {:car_wash => valid_attributes}, valid_session
        }.to change(CarWash, :count).by(1)
      end

      it "assigns a newly created car_wash as @car_wash" do
        post :create, {:car_wash => valid_attributes}, valid_session
        assigns(:car_wash).should be_a(CarWash)
        assigns(:car_wash).should be_persisted
      end

      it "redirects to the created car_wash" do
        post :create, {:car_wash => valid_attributes}, valid_session
        response.should redirect_to(CarWash.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car_wash as @car_wash" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarWash.any_instance.stub(:save).and_return(false)
        post :create, {:car_wash => { "title" => "invalid value" }}, valid_session
        assigns(:car_wash).should be_a_new(CarWash)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarWash.any_instance.stub(:save).and_return(false)
        post :create, {:car_wash => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car_wash" do
        car_wash = CarWash.create! valid_attributes
        # Assuming there are no other car_washes in the database, this
        # specifies that the CarWash created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CarWash.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => car_wash.to_param, :car_wash => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested car_wash as @car_wash" do
        car_wash = CarWash.create! valid_attributes
        put :update, {:id => car_wash.to_param, :car_wash => valid_attributes}, valid_session
        assigns(:car_wash).should eq(car_wash)
      end

      it "redirects to the car_wash" do
        car_wash = CarWash.create! valid_attributes
        put :update, {:id => car_wash.to_param, :car_wash => valid_attributes}, valid_session
        response.should redirect_to(car_wash)
      end
    end

    describe "with invalid params" do
      it "assigns the car_wash as @car_wash" do
        car_wash = CarWash.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarWash.any_instance.stub(:save).and_return(false)
        put :update, {:id => car_wash.to_param, :car_wash => { "title" => "invalid value" }}, valid_session
        assigns(:car_wash).should eq(car_wash)
      end

      it "re-renders the 'edit' template" do
        car_wash = CarWash.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarWash.any_instance.stub(:save).and_return(false)
        put :update, {:id => car_wash.to_param, :car_wash => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car_wash" do
      car_wash = CarWash.create! valid_attributes
      expect {
        delete :destroy, {:id => car_wash.to_param}, valid_session
      }.to change(CarWash, :count).by(-1)
    end

    it "redirects to the car_washes list" do
      car_wash = CarWash.create! valid_attributes
      delete :destroy, {:id => car_wash.to_param}, valid_session
      response.should redirect_to(car_washes_url)
    end
  end

end
